global:
  scrape_interval: 1s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']

  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']

  - job_name: 'host1'
    static_configs:
      - targets: ['192.168.7.91:9100']

  - job_name: 'host1_cadvisor'
    static_configs:
      - targets: ['192.168.7.90:8080']

  - job_name: 'host2'
    static_configs:
      - targets: ['192.168.7.92:9100']

  - job_name: 'host2_cadvisor'
    static_configs:
      - targets: ['192.168.7.92:8080']

  - job_name: 'host3'
    static_configs:
      - targets: ['192.168.7.93:9100']

  - job_name: 'host3_cadvisor'
    static_configs:
      - targets: ['192.168.7.93:8080']
